config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#new"
  resources :articles
  resources :image_galleries do
    member do
      delete 'delete_image/:image_id', to: 'image_galleries#delete_image', as: 'delete_image'
      patch 'move_image/:image_id', to: 'image_galleries#move_image', as: 'move_image'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  include ActiveStorageSupport::SupportForBase64
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_one :image_gallery, as: :galleryable, dependent: :destroy
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :image_gallery, optional: true
  has_one_base64_attached :picture

  # This allows images to be ordered within their gallery thanks to the acts_as_list gem
  acts_as_list scope: :image_gallery

  # Before destroying an image record, the associated picture file is removed from storage.
  before_destroy :purge_picture

  private

  def purge_picture
    picture.purge if picture.attached?
  end
end

app/models/image_gallery.rb
class ImageGallery < ApplicationRecord
  # A polymorphic association, so a gallery can belong to more than one type of model.
  # The 'optional: true' flag allows for flexibility, in case the gallery gets created before the main object.
  belongs_to :galleryable, polymorphic: true, optional: true 

  # A one-to-many relationship with Images. 
  # The acts_as_list gem is used for ordering the images.
  has_many :images, -> { order(position: :asc) }, dependent: :destroy

  # Enables the creation, updating, and deletion of associated images through the ImageGallery form.
  accepts_nested_attributes_for :images, allow_destroy: true, reject_if: :all_blank
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private

  def associate_image_gallery_with(galleryable)
    image_gallery = ImageGallery.find(params[:image_gallery_id])

    # checking for association to not allow "stealing" an existing gallery from another object
    image_gallery.update(galleryable: @article) if image_gallery.galleryable_id.blank?
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all.includes({:image_gallery => :images}).last(3)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      # tying the image gallery to the article
      associate_image_gallery_with(@article) if params[:image_gallery_id].present?
      redirect_to articles_path
    else
      render :new
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :text, :image_gallery_id)
  end

end

app/controllers/image_galleries_controller.rb
class ImageGalleriesController < ApplicationController

  before_action :set_gallery, only: %i[show update delete_image, move_image]
  before_action :set_image, only: %i[delete_image, move_image]

  def show; end 

  def new
    @image_gallery = ImageGallery.new()
    @image_gallery.images.build
  end

  def create
    # if multiple images are uploaded at once, the pictures will be nested in an array
    # "images_attributes" => { "0" => { "picture" => [image, image2, image3] ...
    # this will be rejected, so we need to restructure the params hash
    handle_multiple_images if params[:image_gallery][:images_attributes]["0"][:picture].is_a?(Array)
    @image_gallery = ImageGallery.new(image_gallery_params)

    respond_to do |format|
      if @image_gallery.save
        format.html {redirect_to image_gallery_path(@image_gallery)}
      else
        format.html {render :new, status: :unprocessable_entity}
      end
    end 
  end

  def update
    index = params[:image_gallery][:images_attributes].keys.last
    handle_multiple_images if params[:image_gallery][:images_attributes][index][:picture].is_a?(Array)

    respond_to do |format|
      if @image_gallery.update(image_gallery_params)
        format.html {redirect_to image_gallery_path(@image_gallery)}
      else
        format.html {render :edit, status: :unprocessable_entity}
      end
    end 
  end

  def delete_image
    @image.destroy
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.remove("image_#{@image.id}")
      end
      format.html { redirect_to image_gallery_path(@image_gallery) }
    end
  end

  def move_image
    @image.insert_at(params[:position].to_i) #insert_at is a method from the acts_as_list gem
    head :ok #send back 200 
  end

  private

  def handle_multiple_images
    # user might have already uploaded some images, so we get the last index
    index = params[:image_gallery][:images_attributes].keys.last
    pictures = params[:image_gallery][:images_attributes][index][:picture]
    
    restructured_pictures = 
      pictures.each_with_index.map do |picture, index|
        [index.to_s, { picture: picture }]
      end
    
    # "images_attributes" => { "0" => { "picture": image }, "1" => { "picture": image2 } ...
    params[:image_gallery][:images_attributes] = restructured_pictures.to_h
  end

  def set_gallery
    @image_gallery = ImageGallery.find(params[:id])
  end

  def set_image
    @image = Image.find(params[:image_id])
  end

  def image_gallery_params
    params.require(:image_gallery).permit(:galleryable_id, :galleryable_type, images_attributes: [:id, :picture])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.erb
<div>
  <h1>Articles</h1>

  <% @articles.each do |article| %>
    <div class="border rounded p-3 my-2">
      <h2><%= article.title %></h2>
      <p><%= article.text %></p>

      <% if article.image_gallery.present? %>
        <div class="d-flex align-items-center justify-content-center">
          <% article.image_gallery.images.each do |image| %>
            <%= image_tag(image.picture, :height => "200px") %>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>

  <div class="text-center my-3">
    <%= link_to 'New article', new_article_path(), class:"button" %>
  </div>

</div>

app/views/articles/new.html.erb
<div>
  <h1>New article</h1>
  <%= form_with(model: @article) do |form| %>

    <div class="d-flex flex-column">
      <%= form.label :title %>
      <%= form.text_field :title, class:"my-2 border border-none rounded"  %>
      <%= form.label :text %>
      <%= form.text_area :text, class:"my-2 border border-none rounded" %>
    </div>

    <%= turbo_frame_tag 'image_gallery', src: new_image_gallery_path %>

    <div class="d-flex justify-content-center my-2">
      <%= form.submit %>
    </div>

  <% end %> 
</div>

app/views/image_galleries/_form.html.erb
<%= form_with(model: image_gallery, local: true, multipart: true, html: {"data-controller" => "multi-upload"}) do |form| %>
  <%= form.fields_for :images do |images| %>
    <div class="button position-relative  p-0 m-0 mb-4" data-multi-upload-target= "inputButton">
        <div class="position-absolute w-100 h-100 d-flex align-items-center justify-content-center">
          Add images
        </div>
        <%= images.file_field :picture, 
        direct_upload: true, 
        multiple: true, 
        class: "opacity-0 w-100 h-100 my-2", 
        data: {"multi-upload-target": "files", "action": "input->multi-upload#submitOnInput"} 
        %>
    </div>
  <% end %>
  <%= form.submit 'Add', data: {"multi-upload-target" => "submitButton"}, class:"d-none" %>
<% end %>

app/views/image_galleries/_image.html.erb
<div data-id="<%= image.id %>" class="col-12 p-2 my-1 border rounded" >
  <div class="d-flex justify-content-between align-items-center">
    <%= image_tag(image.picture, :height => "40px") %>
    <p class="text-sm mb-0"><%= image.picture.filename.to_s %> </p>
    <%= link_to('Delete', delete_image_image_gallery_path(@image_gallery, image), method: :delete) %>
  </div>
</div>

app/views/image_galleries/new.html.erb
<%= turbo_frame_tag 'image_gallery' do %>
  <div>
    <h6>Add images</h6>
    <%= render 'form', image_gallery: @image_gallery %>
  </div>
<% end %>

app/views/image_galleries/show.html.erb
<%= turbo_frame_tag 'image_gallery' do %>
  <h6>Uploaded images</h6>
  <p> Drag to reorder existing images</p>
  <div data-controller="drag" data-drag-url="/image_galleries/<%= @image_gallery.id %>/move_image/:id">
    <% @image_gallery.images.each do |image| %>
      <%= render partial: 'image', locals: { image: image} %>
    <% end %> 
  </div>
  <%= render partial: 'form', locals: { image_gallery: @image_gallery } %> <%# to be able to add more images %>
  <%# image_gallery_id is picked up by the parent object's controller to be able to create the association %>
  <%= hidden_field_tag :image_gallery_id, @image_gallery.id %> 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Image Upload Demo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="content">
      <%= yield %>
    </div>
  </body>
</html>